name: UI tests

on:
  push:
    branches: [main, master, work]
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull browser image
        run: docker pull selenoid/chrome:128.0

      - name: Run tests in Docker Compose
        run: docker compose up --build --abort-on-container-exit --exit-code-from tests

      - name: Install Allure commandline
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
